### ISSUE TITLE
[Enigma] Копирование потоков

### ISSUE THREAD

**Issue by pavel-b-novikov** [Romchela/nsudotnet#1]
Серьезно? Через Write?

**Comment by Romchela** [comment]
fixed
https://github.com/Romchela/nsudotnet/blob/master/Vishnevsky.Nsudotnet.Enigma/FileEncryptor.cs#L97

**Comment by pavel-b-novikov** [comment]
А Close зачем вызываете?

**Comment by Romchela** [comment]
удалил
