### ISSUE TITLE
[Enigma] Печать помощи по использованию

### ISSUE THREAD

**Issue by pavel-b-novikov** [Romchela/nsudotnet#4]
А сделайте так, чтобы вместо захардкоженного ```crypto.exe``` выводилось реально имя, которое в данный момент у exe-шника

**Comment by Romchela** [comment]
fixed
https://github.com/Romchela/nsudotnet/blob/master/Vishnevsky.Nsudotnet.Enigma/CommandLineParser.cs#L47-L48
