### ISSUE TITLE
[NumberGuesser] Сообщения

### ISSUE THREAD

**Issue by pavel-b-novikov** [Romchela/nsudotnet#5]
Сделайте как-то разнообразнее, чтобы в сообщении использовалось введенное имя пользователя (при том не фиксировано в начале/в конце, а в разных местах)

**Comment by Romchela** [comment]
fixed
https://github.com/Romchela/nsudotnet/blob/master/Vishnevsky.Nsudotnet.NumberGuesser/Program.cs#L11
